# Generated by Django 5.0.7 on 2024-09-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaylen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
