# Generated by Django 5.0.7 on 2024-09-04 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaylen', '0002_delete_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_cursos')),
                ('curso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_curso', to='AppMaylen.curso')),
            ],
        ),
    ]
