# Generated by Django 5.0.7 on 2024-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaylen', '0003_imagencurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='curso_imagenes/'),
        ),
        migrations.DeleteModel(
            name='ImagenCurso',
        ),
    ]
