# Generated by Django 5.0.7 on 2024-09-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaylen', '0004_curso_imagen_delete_imagencurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.CharField(default='No definido', max_length=40),
        ),
    ]
