# Generated by Django 5.0.7 on 2024-09-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaylen', '0006_curso_autor_curso_fecha_alter_curso_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profesor_imagenes/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
    ]
